import {
  SkinConcern,
  ServiceItem,
  JourneyStep,
  EduTopic,
  MythFact,
  FAQItem,
  DoctorProfile,
} from "./types";

export const DOCTOR_PROFILE: DoctorProfile = {
  name: "Dr. Priyanka Rahul Patil",
  title: "Cosmetology Consultant | Skin, Hair & Laser Treatment",
  qualification: "BAMS",
  experience: "10+ Years Clinical Cosmetology & Skin, Hair, Laser Practice",
  bio: "Dr. Priyanka Rahul Patil is recognized as a leading Cosmetology Consultant and Skin, Hair & Laser specialist in Virar West, bringing over 10+ years of clinical expertise in medical cosmetology, trichology, laser aesthetics, and integrative skin health. Dedicated to patient-centric, evidence-based care, she evaluates the root factors behind every skin and scalp condition to design structured, highly personalized clinical treatment plans.",
  specialties: [
    "Cosmetology Consultant in Virar West",
    "Medical & Clinical Cosmetology",
    "Acne & Scar Management",
    "Pigmentation & Melasma Care",
    "Skin, Hair & Laser Treatment",
    "Trichology & Hair Regrowth PRP",
    "Preventive Barrier Care",
  ],
  image: "/images/doctor.jpg",
  clinicAddress: "Shop No. 32, Agarwal Lifestyle Avenue, C-3, Opp. Poonam Vista, Global City, Virar West, Maharashtra 401303",
  phone: "+91 72493 12567",
  whatsapp: "+917249312567",
  email: "hello@cozpiraaclinic.com",
  hours: "Monday – Saturday: 10:00 AM – 8:00 PM (Closed on Sundays)",
};

export const SKIN_CONCERNS: SkinConcern[] = [
  {
    id: "acne",
    title: "Acne",
    category: "Acne",
    summary: "Inflammatory or non-inflammatory follicular breakouts caused by excess sebum and micro-comedones.",
    explanation: "Acne occurs when hair follicles become clogged with oil, dead skin cells, and bacteria. It can range from mild papules and blackheads to painful cystic nodules requiring medical evaluation.",
    keyCharacteristics: ["Comedones & Papules", "Localized Inflammation", "Oil Gland Overactivity"],
    treatmentCategories: ["Topical Prescription Therapy", "Comedone Extraction", "Chemical Resurfacing"],
    medicalDisclaimer: "Treatment recommendations are determined following a physical skin evaluation and clinical consultation.",
  },
  {
    id: "acne-scars",
    title: "Acne Scars",
    category: "Acne",
    summary: "Post-inflammatory structural changes, including icepick, rolling, boxcar scars, or hyperpigmentation.",
    explanation: "Scars form when deep dermal tissue experiences collagen damage during inflammatory acne healing. Treatment focuses on collagen remodeling and surface texture smoothing.",
    keyCharacteristics: ["Atrophic Depressions", "Textural Irregularities", "Post-Inflammatory Changes"],
    treatmentCategories: ["Subcision & Microneedling", "Laser Resurfacing", "PRP Regenerative Therapy"],
    medicalDisclaimer: "Scar management requires progressive multi-session clinical protocols tailored to scar type.",
  },
  {
    id: "pigmentation",
    title: "Pigmentation",
    category: "Pigmentation",
    summary: "Irregular melanin distribution resulting in localized skin darkening or uneven patchiness.",
    explanation: "Hyperpigmentation develops when melanocytes produce excess melanin in response to UV exposure, hormonal shifts, or skin trauma.",
    keyCharacteristics: ["Darkened Patches", "Sun-Exposed Aggravation", "Uneven Melanin Density"],
    treatmentCategories: ["Depigmenting Topicals", "Targeted Chemical Peels", "Laser Toners"],
    medicalDisclaimer: "Sun protection and strict compliance are vital for long-term pigmentation balance.",
  },
  {
    id: "melasma",
    title: "Melasma",
    category: "Pigmentation",
    summary: "Symmetrical facial hyperpigmentation triggered by hormonal fluctuations and light exposure.",
    explanation: "Melasma typically presents as brown or blue-gray patches on the cheeks, forehead, and upper lip. It requires gentle, controlled clinical skin care to prevent rebound darkening.",
    keyCharacteristics: ["Symmetrical Pattern", "Hormonal Sensitivity", "Dermal & Epidermal Component"],
    treatmentCategories: ["Barrier Repair Protocols", "Gentle Chemical Exfoliation", "Oral/Topical Maintenance"],
    medicalDisclaimer: "Melasma requires ongoing maintenance and continuous UV broad-spectrum protection.",
  },
  {
    id: "dark-spots",
    title: "Dark Spots",
    category: "Pigmentation",
    summary: "Focused solar lentigines or post-inflammatory marks from resolved blemishes.",
    explanation: "Individual dark spots are concentrated clusters of melanin. Identifying whether a mark is epidermal or dermal dictates the choice of clinical treatment.",
    keyCharacteristics: ["Discrete Spots", "Sun Damage Accumulation", "Post-Breakout Remnants"],
    treatmentCategories: ["Targeted Spot Peels", "Precision Laser Therapy", "Brightening Serums"],
    medicalDisclaimer: "Early clinical skin assessment ensures correct differentiation from dysplastic lesions.",
  },
  {
    id: "uneven-tone",
    title: "Uneven Skin Tone",
    category: "Pigmentation",
    summary: "Loss of uniform complexion clarity due to cumulative environmental stress and micro-inflammation.",
    explanation: "Uneven skin tone occurs when dead skin accumulation, mild UV damage, and vascular reactivity disrupt the smooth reflection of light across the face.",
    keyCharacteristics: ["Dullness", "Patchy Discoloration", "Lack of Natural Luminosity"],
    treatmentCategories: ["Hydrating Micro-Peels", "Cellular Turnover Agents", "Photofacial Rejuvenation"],
    medicalDisclaimer: "Uniformity is restored through customized daily routines and periodic clinical care.",
  },
  {
    id: "sensitive-skin",
    title: "Sensitive Skin",
    category: "Texture",
    summary: "Hyper-reactive skin exhibiting redness, stinging, or compromised epidermal barrier integrity.",
    explanation: "Sensitized skin has a disrupted lipid barrier, allowing moisture to escape and irritants to enter. Restoring barrier lipid architecture is the primary medical goal.",
    keyCharacteristics: ["Erythema (Redness)", "Barrier Disruption", "Reactivity to Actives"],
    treatmentCategories: ["Barrier Repair Therapy", "Calming Formulations", "Minimalist Clinical Skincare"],
    medicalDisclaimer: "Avoid harsh scrubs or aggressive actives until barrier repair is established.",
  },
  {
    id: "dry-skin",
    title: "Dry Skin",
    category: "Texture",
    summary: "Lipid deficiency leading to flaking, tightness, reduced elasticity, and premature fine lines.",
    explanation: "Dry skin lacks necessary natural sebum to seal in hydration, weakening epidermal elasticity and predisposing the skin to micro-fissures and irritation.",
    keyCharacteristics: ["Scaling & Tightness", "Impaired Sebum Production", "Rough Surface Feel"],
    treatmentCategories: ["Lipid-Replenishing Therapies", "Deep Hydro-Dermal Care", "Ceramide-Rich Protocols"],
    medicalDisclaimer: "Dry skin differs from dehydrated skin; accurate diagnosis guides ingredient choice.",
  },
  {
    id: "oily-skin",
    title: "Oily Skin",
    category: "Texture",
    summary: "Excessive sebaceous gland activity causing persistent shine, enlarged pores, and congestion.",
    explanation: "Overactive sebaceous glands can be driven by genetics, climate, or hormonal signals. Balancing oil without stripping essential moisture is key.",
    keyCharacteristics: ["Enlarged Visible Pores", "Persistent Shine", "Prone to Comedones"],
    treatmentCategories: ["Sebum-Regulating Actives", "Pore-Refining Peels", "Non-Comedogenic Hydration"],
    medicalDisclaimer: "Over-cleansing can trigger rebound oil production; clinical balance is recommended.",
  },
  {
    id: "skin-texture",
    title: "Skin Texture",
    category: "Texture",
    summary: "Rough, uneven surface terrain caused by slowed cellular turnover or keratosis pilaris.",
    explanation: "Irregular skin texture occurs when dead corneocytes build up faster than they shed, resulting in a dull, coarse, or bumpy tactile feel.",
    keyCharacteristics: ["Bumpy Surface", "Slow Cell Turnover", "Lack of Smoothness"],
    treatmentCategories: ["Medical-Grade Micro-Exfoliation", "Polishing Peels", "Retinoid Conditioning"],
    medicalDisclaimer: "Clinical exfoliants must be calibrated to your specific skin thickness.",
  },
  {
    id: "fine-lines",
    title: "Fine Lines",
    category: "Aging",
    summary: "Early superficial creasing caused by natural collagen degradation and photo-aging.",
    explanation: "As collagen and elastin synthesis slows down with age and UV exposure, shallow lines form around motion zones such as eyes and forehead.",
    keyCharacteristics: ["Superficial Creasing", "Decreased Skin Elasticity", "Dehydration Aggravation"],
    treatmentCategories: ["Collagen Stimulation Therapy", "Anti-Aging Peels", "Hydro-Nourishing Micro-Injections"],
    medicalDisclaimer: "Early preventive care produces optimal long-term structural retention.",
  },
  {
    id: "hair-scalp",
    title: "Hair & Scalp Concerns",
    category: "Scalp",
    summary: "Hair thinning, excessive shedding, scalp flaking, and follicular miniaturization.",
    explanation: "Scalp health directly governs hair hair cycle quality. Conditions like telogen effluvium, androgenetic thinning, and scalp dermatitis require targeted trichological care.",
    keyCharacteristics: ["Excessive Hair Shedding", "Widening Parting", "Scalp Inflammation or Flaking"],
    treatmentCategories: ["PRP Scalp Therapy", "Trichological Scalp Detox", "Follicular Growth Stimulants"],
    medicalDisclaimer: "Early intervention yields significantly higher follicle preservation.",
  },
];

export const CLINICAL_SERVICES: ServiceItem[] = [
  {
    id: "acne-management",
    title: "Acne Management",
    shortDesc: "Comprehensive clinical care to control active breakouts, soothe inflammation, and prevent long-term scarring.",
    fullDesc: "Our medical acne care program evaluates hormonal, lifestyle, and clinical skin causes of acne. By combining clinical topical therapies, gentle extractions, and anti-inflammatory care, we clear active lesions while shielding your skin from scar formation.",
    iconName: "Sparkles",
    keyBenefits: ["Clears Active Breakouts", "Reduces Redness & Inflammation", "Prevents Post-Acne Scars"],
    targetConcerns: ["Acne", "Oily Skin", "Dark Spots"],
    overview: "Involves thorough skin cleansing, comedone extraction if required, tailored topical application, and personalized home-care guidance.",
  },
  {
    id: "acne-scar-management",
    title: "Acne Scar Management",
    shortDesc: "Advanced multi-modality structural treatment to remodel collagen and smooth scar depressions.",
    fullDesc: "Acne scars require multi-layered treatment. We combine subcision, targeted microneedling, chemical resurfacing, and PRP therapy to stimulate new collagen production, restoring smooth skin contours.",
    iconName: "Layers",
    keyBenefits: ["Smooths Scar Contours", "Stimulates Natural Collagen", "Refines Overall Skin Texture"],
    targetConcerns: ["Acne Scars", "Skin Texture"],
    overview: "Progressive sessions planned at 3 to 4 week intervals to allow optimal collagen remodeling.",
  },
  {
    id: "pigmentation-melasma-care",
    title: "Pigmentation & Melasma Care",
    shortDesc: "Specialized clinical depigmentation therapies targeting epidermal and dermal melanin overproduction.",
    fullDesc: "Pigmentation demands gentle, precise management. Our targeted peels and medical depigmenting regimens regulate melanocyte activity, fading dark patches without damaging surrounding healthy tissue.",
    iconName: "Sun",
    keyBenefits: ["Evens Skin Tone", "Targets Deep Melanin Deposits", "Gentle Rebound-Safe Protocols"],
    targetConcerns: ["Pigmentation", "Melasma", "Dark Spots", "Uneven Skin Tone"],
    overview: "Includes detailed patch evaluation, superficial-to-medium depth chemical peels, and strict UV management guidance.",
  },
  {
    id: "skin-rejuvenation",
    title: "Skin Rejuvenation",
    shortDesc: "Revitalizing clinical treatments designed to restore natural glow, elasticity, and cellular vitality.",
    fullDesc: "Combating dullness and environmental exhaustion, our rejuvenation protocols enhance cellular turnover, restore skin hydration, and leave the skin feeling refined, fresh, and supple.",
    iconName: "Zap",
    keyBenefits: ["Restores Natural Luminosity", "Hydrates Deep Epidermal Layers", "Refines Fine Lines"],
    targetConcerns: ["Uneven Skin Tone", "Dry Skin", "Skin Texture"],
    overview: "Uses nutrient-dense clinical infusions, gentle enzymatic exfoliation, and targeted restorative masks.",
  },
  {
    id: "sensitive-skin-care",
    title: "Sensitive Skin Care",
    shortDesc: "Calming medical therapy to soothe erythema, rebuild lipid barrier integrity, and reduce reactivity.",
    fullDesc: "Compromised skin barriers cause chronic stinging, redness, and sensitivity. We prioritize barrier lipid repair using hypoallergenic, anti-inflammatory clinical formulations that build resilience over time.",
    iconName: "ShieldCheck",
    keyBenefits: ["Soothes Irritation & Redness", "Strengthens Epidermal Barrier", "Builds Long-Term Resilience"],
    targetConcerns: ["Sensitive Skin", "Dry Skin"],
    overview: "Non-ablative, deeply soothing treatment focused on ceramide replenishment and barrier protection.",
  },
  {
    id: "anti-ageing-treatment",
    title: "Anti-Ageing Skin Care",
    shortDesc: "Evidence-based structural care to minimize fine lines, restore skin firmness, and support structural collagen.",
    fullDesc: "Ageing is a natural process that can be supported gracefully. Our clinical anti-ageing care focuses on preserving dermal density, promoting cellular repair, and softening early expressive lines.",
    iconName: "Clock",
    keyBenefits: ["Softens Fine Lines", "Supports Dermal Firmness", "Promotes Cell Renewal"],
    targetConcerns: ["Fine Lines", "Skin Texture"],
    overview: "Incorporates retinoid conditioning, peptide infusions, and restorative collagen stimulation therapies.",
  },
  {
    id: "hair-scalp-care",
    title: "Hair & Scalp Care",
    shortDesc: "Trichological clinical treatments and PRP therapy to control hair loss and stimulate dormant follicles.",
    fullDesc: "Healthy hair originates from a healthy scalp environment. We evaluate scalp health, follicular density, and systemic factors, offering targeted treatments including Platelet-Rich Plasma (PRP) therapy to revitalize thinning hair.",
    iconName: "Activity",
    keyBenefits: ["Stops Excessive Shedding", "Stimulates Hair Follicles", "Improves Scalp Environment"],
    targetConcerns: ["Hair & Scalp Concerns"],
    overview: "Includes trichoscopy scalp evaluation, specialized scalp cleansing, and targeted PRP micro-administrations.",
  },
  {
    id: "laser-skin-hair-treatment",
    title: "Laser Skin & Hair Treatment",
    shortDesc: "Precise light-based procedures for targeted skin resurfacing, pigmentation removal, and hair reduction.",
    fullDesc: "Utilizing precise laser technology, our clinical laser protocols safely address stubborn pigmentation, facial redness, micro-veins, and unwanted facial hair with minimal downtime.",
    iconName: "Target",
    keyBenefits: ["Precision Target Accuracy", "Minimal Surrounding Tissue Impact", "Long-Lasting Clinical Results"],
    targetConcerns: ["Pigmentation", "Dark Spots", "Hair & Scalp Concerns"],
    overview: "Conducted under strict clinical safety standards with pre-laser skin conditioning.",
  },
  {
    id: "clinical-skin-treatments",
    title: "Clinical Skin Treatments",
    shortDesc: "Customized skin and cosmetology procedures addressing specific skin conditions with clinical precision.",
    fullDesc: "From specialized comedone management to medical-grade facial conditioning, our clinical treatments are tailored precisely to your immediate skin consultation diagnosis.",
    iconName: "Stethoscope",
    keyBenefits: ["Physician-Guided Care", "Customized Formulation", "High Safety Profile"],
    targetConcerns: ["Acne", "Dry Skin", "Oily Skin"],
    overview: "Every procedure begins with a physical skin assessment to select ideal clinical actives.",
  },
  {
    id: "preventive-skin-care",
    title: "Preventive Skin Care",
    shortDesc: "Proactive care strategies to protect skin health, prevent photo-damage, and maintain long-term results.",
    fullDesc: "Preventive skin care is the cornerstone of lifelong healthy skin. We guide patients in developing resilient daily routines, solar protection habits, and seasonal skincare adaptations.",
    iconName: "CheckCircle2",
    keyBenefits: ["Prevents Premature Photo-Aging", "Maintains Barrier Health", "Saves Time & Long-Term Effort"],
    targetConcerns: ["Fine Lines", "Uneven Skin Tone", "Sensitive Skin"],
    overview: "Focuses on comprehensive routine audit, ingredient guidance, and customized daily solar defense.",
  },
];

export const DERMATOLOGY_SERVICES = CLINICAL_SERVICES;

export const PATIENT_JOURNEY: JourneyStep[] = [
  {
    step: "01",
    number: "01",
    title: "Consultation",
    shortDesc: "In-depth conversation exploring your skin history, lifestyle, current routine, and primary concerns.",
    detailedDesc: "Your journey begins with a thorough 1-on-1 consultation with Dr. Priyanka. We review your skin and hair history, previous treatments, diet, and daily routine without rushed judgments.",
    deliverables: ["History Mapping", "Routine Review", "Initial Concern Alignment"],
  },
  {
    step: "02",
    number: "02",
    title: "Skin Assessment",
    shortDesc: "Comprehensive visual examination of your skin barrier, lipid balance, and underlying concerns.",
    detailedDesc: "Using visual and clinical diagnostic methods, we examine your skin type, moisture retention capacity, pigmentation depth, and pore dynamics to establish an accurate diagnosis.",
    deliverables: ["Barrier Status Evaluation", "Pigmentation & Texture Check", "Clinical Diagnosis"],
  },
  {
    step: "03",
    number: "03",
    title: "Personalized Plan",
    shortDesc: "Design of an evidence-based care strategy tailored specifically to your skin and lifestyle.",
    detailedDesc: "We curate a straightforward, non-overwhelming treatment roadmap outlining clinical procedures, home care instructions, ingredient guidelines, and clear timelines.",
    deliverables: ["Customized Home Routine", "Clinical Procedure Roadmap", "Transparent Guidance"],
  },
  {
    step: "04",
    number: "04",
    title: "Treatment & Monitoring",
    shortDesc: "Gentle administration of clinical care with continuous monitoring of your skin's response.",
    detailedDesc: "Clinical treatments are performed with high hygiene and care standards. We track how your skin responds and fine-tune formulations as your skin improves.",
    deliverables: ["Safe Clinical Procedures", "Progress Tracking", "Adaptive Adjustments"],
  },
  {
    step: "05",
    number: "05",
    title: "Follow-Up Care",
    shortDesc: "Long-term maintenance guidance to protect your results and sustain healthy skin barrier function.",
    detailedDesc: "Healthy skin requires ongoing care. Follow-up visits ensure your results are sustained and your skin barrier remains protected through seasonal shifts.",
    deliverables: ["Maintenance Protocols", "Seasonal Routine Adjustments", "Ongoing Doctor Support"],
  },
];

export const EDU_TOPICS: EduTopic[] = [
  {
    id: "why-acne-happens",
    title: "Why Acne Happens",
    category: "Acne Fundamentals",
    readTime: "3 min read",
    summary: "Understanding the biological chain reaction behind clogged pores and inflammatory acne lesions.",
    content: [
      {
        heading: "The Four Key Factors",
        body: "Acne is not caused by dirty skin. It is driven by four primary factors: excess sebum production, follicular hyperkeratinization (sticky skin cells clogging pores), bacterial proliferation (C. acnes), and localized inflammation.",
      },
      {
        heading: "Hormones & Sebum",
        body: "Fluctuations in androgen hormones stimulate oil glands to produce thicker sebum. When combined with un-shed dead skin cells, micro-comedones form beneath the surface.",
      },
      {
        heading: "The Medical Approach",
        body: "Effective acne care targets excess oil, accelerates cell turnover, and calms inflammation without stripping the protective skin barrier.",
      },
    ],
    keyTakeaway: "Acne is an inflammatory follicular condition requiring gentle, consistent care—not harsh scrubbing.",
  },
  {
    id: "understanding-pigmentation",
    title: "Understanding Pigmentation",
    category: "Skin Tone Care",
    readTime: "4 min read",
    summary: "How melanocytes respond to UV rays, hormones, and inflammation by producing excess melanin.",
    content: [
      {
        heading: "Melanin Production",
        body: "Melanocytes produce melanin to shield skin cell nuclei from ultraviolet radiation. When overstimulated by sun, heat, or trauma, excess pigment clusters in patches.",
      },
      {
        heading: "Epidermal vs. Dermal",
        body: "Epidermal pigmentation sits near the surface and responds well to topical exfoliants and peels. Dermal pigmentation lies deeper and requires patient, long-term care.",
      },
    ],
    keyTakeaway: "Broad-spectrum SPF 30+ protection daily is mandatory for treating and preventing hyperpigmentation.",
  },
  {
    id: "what-causes-acne-scars",
    title: "What Causes Acne Scars",
    category: "Scar Science",
    readTime: "3 min read",
    summary: "The structural collagen disruption left behind after severe or squeezed acne lesions.",
    content: [
      {
        heading: "Collagen Disruption",
        body: "Deep inflammatory acne damages the dermal architecture. During healing, if insufficient collagen is produced, atrophic (pitted) scars remain.",
      },
      {
        heading: "Why Squeezing Worsens Scars",
        body: "Popping blemishes ruptures the follicle wall internally, forcing inflammatory fluid deeper into the dermis and drastically increasing scar likelihood.",
      },
    ],
    keyTakeaway: "Never squeeze active blemishes. Early medical acne control is the best defense against permanent scarring.",
  },
  {
    id: "skin-barrier-basics",
    title: "Skin Barrier Basics",
    category: "Barrier Health",
    readTime: "3 min read",
    summary: "The stratum corneum is your skin's natural shield against hydration loss and external irritants.",
    content: [
      {
        heading: "The Brick and Mortar Structure",
        body: "Think of your skin cells as bricks and natural lipids (ceramides, cholesterol, fatty acids) as mortar. A healthy barrier keeps hydration in and irritants out.",
      },
      {
        heading: "Signs of a Damaged Barrier",
        body: "Stinging upon product application, persistent redness, unexpected flaking, and heightened reactivity indicate a compromised lipid barrier.",
      },
    ],
    keyTakeaway: "When in doubt, pause active exfoliants and focus exclusively on hydrating barrier repair.",
  },
  {
    id: "sun-protection",
    title: "Sun Protection Essentials",
    category: "Preventive Care",
    readTime: "4 min read",
    summary: "Why broad-spectrum UV protection is the single most important step for skin longevity.",
    content: [
      {
        heading: "UVA vs. UVB Rays",
        body: "UVB rays cause sunburn and heat damage. UVA rays penetrate clouds and window glass, reaching deep into the dermis to break down collagen and trigger dark spots.",
      },
      {
        heading: "Application & Reapplication",
        body: "Apply two fingers' length of broad-spectrum SPF 30 or higher 15 minutes before stepping out, and reapply every 2 to 3 hours during prolonged sun exposure.",
      },
    ],
    keyTakeaway: "Sunscreen is a daily year-round medical necessity, not a seasonal vacation cosmetic.",
  },
  {
    id: "sensitive-skin-care",
    title: "Sensitive Skin Principles",
    category: "Reactivity & Redness",
    readTime: "3 min read",
    summary: "Navigating hyper-reactive skin with minimal ingredient exposure and barrier fortification.",
    content: [
      {
        heading: "Less is More",
        body: "Sensitive skin thrives on simple, fragrance-free, minimalist routines. Introducing multiple new products simultaneously makes identifying triggers impossible.",
      },
      {
        heading: "Patch Testing",
        body: "Always perform a 48-hour patch test on the inner forearm or side of the neck before applying any new topical product to your face.",
      },
    ],
    keyTakeaway: "Prioritize gentle soothing ingredients like ceramides, centella, and hyaluronic acid over active exfoliants.",
  },
  {
    id: "hair-fall-scalp-health",
    title: "Hair Fall & Scalp Health",
    category: "Trichology Insights",
    readTime: "4 min read",
    summary: "Why scalp nutrition and micro-circulation dictate your hair shedding and regrowth cycles.",
    content: [
      {
        heading: "The Hair Growth Cycle",
        body: "Hair strands pass through Anagen (growth), Catagen (transition), and Telogen (resting/shedding) phases. Stress, nutritional gaps, or illness can shift follicles prematurely into shedding.",
      },
      {
        heading: "PRP & Follicle Support",
        body: "Platelet-Rich Plasma (PRP) therapy delivers concentrated growth factors directly to dormant follicles, extending the growth phase and improving strand thickness.",
      },
    ],
    keyTakeaway: "Addressing scalp inflammation early preserves follicle viability and supports long-term hair density.",
  },
  {
    id: "skincare-mistakes",
    title: "Common Skincare Mistakes",
    category: "Practical Guidance",
    readTime: "3 min read",
    summary: "Frequent skincare errors that lead to irritation, breakout flare-ups, and barrier damage.",
    content: [
      {
        heading: "Over-Exfoliation",
        body: "Using multiple chemical acids daily strips natural protective lipids, leaving skin vulnerable to inflammation and rebound acne.",
      },
      {
        heading: "Ignoring Product Layering",
        body: "Apply products from thinnest to thickest consistency: cleanser, hydrating toner/serum, treatment active, moisturizer, and sunscreen.",
      },
    ],
    keyTakeaway: "Consistency with appropriate products beats aggressive, unpredictable routine changes.",
  },
];

export const MYTHS_VS_FACTS: MythFact[] = [
  {
    id: "myth-1",
    myth: "More skincare products always mean faster and better skin results.",
    fact: "A simple, well-chosen routine tailored to your skin barrier produces far safer and more reliable results than stacking multiple active products.",
    category: "Routine Simplicity",
    insight: "Overloading active ingredients causes barrier disruption, increased reactivity, and unexpected breakout flare-ups.",
  },
  {
    id: "myth-2",
    myth: "Sunscreen is only required when outdoors on bright, sunny days.",
    fact: "UVA rays penetrate clouds and window glass every day, causing silent collagen loss and dark spots regardless of weather.",
    category: "Sun Defense",
    insight: "Daily broad-spectrum sunscreen application is essential for preventing long-term photo-aging and pigmentation.",
  },
  {
    id: "myth-3",
    myth: "Popping or squeezing pimples makes them clear up faster.",
    fact: "Squeezing forces bacterial inflammation deeper into dermal layers, leading to longer healing times and high scar risk.",
    category: "Acne Care",
    insight: "Clinical spot care and gentle topical treatments clear lesions without risking permanent scarring.",
  },
  {
    id: "myth-4",
    myth: "Oily skin does not require moisturizer.",
    fact: "Oily skin often lacks hydration (water balance). Skipping moisturizer forces oil glands to produce even more sebum.",
    category: "Skin Hydration",
    insight: "Lightweight, non-comedogenic gel moisturizers balance oil production while keeping skin hydrated.",
  },
  {
    id: "myth-5",
    myth: "Acne is primarily caused by poor personal hygiene.",
    fact: "Acne is driven by internal factors like hormones, sebum composition, and follicular inflammation—not unwashed skin.",
    category: "Acne Myth",
    insight: "Excessive washing or harsh scrubbing irritates skin and aggravates acne breakouts.",
  },
];

export const FAQS: FAQItem[] = [
  {
    id: "faq-best-cosmetologist-virar",
    question: "Who is the best Cosmetology Consultant & Skin, Hair, Laser specialist in Virar West?",
    answer: "Dr. Priyanka Rahul Patil (BAMS) at COZPIRAA Skin, Hair & Laser Clinic is widely recognized as a leading Cosmetology Consultant in Virar West, bringing 10+ years of clinical experience in treating acne, acne scars, hyperpigmentation, melasma, anti-aging, laser treatments, and hair regrowth.",
  },
  {
    id: "faq-location-virar",
    question: "Where is COZPIRAA Skin, Hair & Laser Clinic located in Virar?",
    answer: "COZPIRAA is located at Shop No. 32, Agarwal Lifestyle Avenue, C-3, Opp. Poonam Vista, Global City, Virar West, Maharashtra 401303. It serves patients across Virar West, Virar East, Bolinj, Arnala, Agashi, Nallasopara, and Vasai.",
  },
  {
    id: "faq-treatments-offered",
    question: "What skin, hair, laser, and cosmetology services are available at COZPIRAA Virar?",
    answer: "COZPIRAA provides comprehensive clinical skin, hair, laser, and cosmetology treatments including acne control, scar microneedling & subcision, chemical peels, hyperpigmentation & melasma care, laser skin rejuvenation, anti-aging therapies, and PRP hair growth treatment.",
  },
  {
    id: "faq-1",
    question: "How do I book a consultation with Dr. Priyanka Rahul Patil?",
    answer: "You can easily request a consultation online using our appointment form on this website, or call/WhatsApp us directly at +91 72493 12567 during clinic hours (Monday to Saturday, 10:00 AM – 8:00 PM).",
  },
  {
    id: "faq-2",
    question: "What happens during my first skin & cosmetology consultation?",
    answer: "During your initial visit, Dr. Priyanka will conduct a detailed 1-on-1 evaluation of your skin concerns, medical history, lifestyle factors, and current skincare routine. You will receive an accurate assessment and a personalized care plan.",
  },
  {
    id: "faq-3",
    question: "Can I discuss multiple skin & hair concerns during one consultation?",
    answer: "Yes, absolutely. Skin and scalp health are interconnected. We encourage you to share all your skin, hair, or cosmetological concerns so we can curate a holistic, well-coordinated care plan.",
  },
  {
    id: "faq-4",
    question: "How is a treatment plan decided?",
    answer: "Your treatment plan is developed based on a physical skin evaluation, your skin type, lifestyle, severity of concerns, and personal goals. We prioritize safe, evidence-based skin, hair, and cosmetological protocols.",
  },
  {
    id: "faq-5",
    question: "How should I prepare for my consultation at COZPIRAA Virar?",
    answer: "Please come with a clean face (minimal or no makeup if possible), bring a list or photos of your current daily skincare products/medications, and note down any specific questions you wish to ask.",
  },
  {
    id: "faq-6",
    question: "How long does a consultation take?",
    answer: "A comprehensive initial consultation typically takes 20 to 30 minutes to ensure a thorough evaluation, careful explanation of your condition, and ample time to address your questions.",
  },
];
